[
  {
    category: "Photography",
    image: {
      url: "https://www.infodesigners.eu/favicone/favicon.ico",
      alt: "Global Photography Awards Logo",
      imagetag: "Photography Competition",
    },
    title: "2025 Global Photography Awards",
    description:
      "An international photography competition celebrating unique perspectives behind every photograph, open to professionals, amateurs, and students. Participants can showcase their talent globally and compete in multiple categories with the opportunity to gain worldwide recognition.",
    meta: {
      eligibility: "Photographers 18+ (professionals, amateurs, students)",
      ageeligibility: "18+",
      location: "Global",
      mode: "online",
      tags: [
        "Photography",
        "Art",
        "Competition",
        "Global",
        "Amateurs",
        "Professionals",
        "Students",
      ],
    },
    prize: {
      amount: 5000,
      currency: "USD",
      otherbenefits:
        "e-certificates, professional logos, online gallery feature, statuettes",
    },
    startdate: "2025-05-22",
    enddate: "2025-09-12",
    endiso: "2025-09-12",
    link: "https://www.infodesigners.eu/photography-competitions/2025-global-photography-awards",
    skilllevel: "all levels",
    entryfee: "entry fees",
  },
  {
    category: "Architecture",
    image: {
      url: "https://images.unsplash.com/photo-1599693496429-04a43d35a782?q=80&w=2070&auto=format&fit=crop",
      alt: "Architectural design of a modern city market",
      imagetag: "Urban Design",
    },
    statustext: "Open",
    title:
      "International Architectural Competition for The New Vision for the Pazardzhik City Market",
    description:
      "An international competition to find an innovative and functional solution for renovating the City Market in Pazardzhik, Bulgaria, transforming it into the heart of a modern city. The top three projects will be awarded.",
    meta: {
      eligibility: "Architects & urban planners",
      location: "Global",
      mode: "online",
      tags: ["Architecture", "Urban Design", "Concept", "Innovation"],
      prize: {
        amount: 15000,
        currency: "EUR",
      },
      otherbenefits: null,
      startdate: "2025-06-11",
      enddate: "2025-09-01",
      endiso: "2025-09-01",
    },
    link: "https://www.infodesigners.eu/architecture-competitions/international-architectural-competition-for-the-new-vision-for-the-pazardzhik-city-market",
    skilllevel: "advanced",
    entryfee: "no entry fees",
  },
  {
    category: "Writing",
    image: {
      url: "https://images.unsplash.com/photo-1455390582262-044cdead277a?q=80&w=1973&auto=format&fit=crop",
      alt: "A person typing on a vintage typewriter",
      imagetag: "Playwriting",
    },
    statustext: "Open",
    title: "The Yale Drama Series 2026",
    description:
      "An international competition for emerging playwrights to win a $10,000 prize and have their winning play published by Yale University Press. The competition is judged by a preeminent playwright.",
    meta: {
      eligibility: "Emerging playwrights",
      location: "Global",
      mode: "online",
      tags: [
        "Writing",
        "Playwriting",
        "Theater",
        "Competition",
        "Art & Design",
      ],
      prize: {
        amount: 10000,
        currency: "USD",
      },
      otherbenefits: "publication",
      startdate: null,
      enddate: "August 15, 2025",
      endiso: "2025-08-15",
    },
    link: "https://www.infodesigners.eu/writing-competitions/the-yale-drama-series-2026",
    skilllevel: "advanced",
    entryfee: "no entry fees",
  },
  {
    category: "Graphic Design",
    image: {
      url: "https://images.unsplash.com/photo-1626785774573-4b799315345d?q=80&w=2071&auto=format&fit=crop",
      alt: "A collection of colorful logo designs on a mood board",
      imagetag: "Logo Design",
    },
    statustext: "Open",
    title: "16th WOLDA Worldwide Logo Design Award",
    description:
      "An international competition for logos and business stationery, honoring the world's best work in logo design. Winners are published, receive certificates, and gain media coverage.",
    meta: {
      eligibility: "Designers, agencies, clients & students",
      location: "Global",
      mode: "online",
      tags: [
        "Graphic Design",
        "Logo Design",
        "Branding",
        "Award",
        "Competition",
      ],
      prize: {
        amount: 0,
        currency: "N/A",
      },
      otherbenefits: "certificates, publication, media coverage",
      startdate: "2025-06-20",
      enddate: "2025-09-30",
      endiso: "2025-09-30",
    },
    link: "https://www.infodesigners.eu/graphic-design-competitions/16th-wolda-worldwide-logo-design-award",
    skilllevel: "intermediate",
    entryfee: "entry fees",
  },
  {
    category: "Technology",
    image: {
      url: "https://www.veritasai.com/hubfs/veritas-ai-logo-color.svg",
      alt: "Microsoft Imagine Cup Logo",
      imagetag: "Innovation",
    },
    statustext: "Open",
    title: "Microsoft Imagine Cup",
    description:
      "A global technology competition for students to solve real-world problems using Microsoft Azure. The challenge encourages innovation, collaboration, and critical thinking. Benefits include cash prizes, mentorship, and global recognition.",
    meta: {
      eligibility: "Students (high school, undergraduate, graduate)",
      ageeligibility: "16+",
      location: "Global",
      mode: "online",
      tags: [
        "Technology",
        "Students",
        "Innovation",
        "Competition",
        "AI",
        "Microsoft",
      ],
      prize: {
        amount: 100000,
        currency: "USD",
      },
      otherbenefits: "mentorship, Microsoft Azure credits, technical support",
      startdate: null,
      enddate: "January 2026",
      endiso: "2026-01-31",
    },
    link: "https://imaginecup.microsoft.com/en-us",
    skilllevel: "advanced",
    entryfee: "no entry fees",
  },
];
